#!/usr/bin/env python
import json
import sys

from message import message

def readJsonStringFromStdIn():
  return json.loads(sys.stdin.readline().replace('\n', ''))

if __name__ == '__main__':
  functionName = sys.argv[1]
  transformer = message.message()
  exitCode = 1
  try:
    if (functionName == 'loadNestedEvent'):
      event = readJsonStringFromStdIn()
      context = readJsonStringFromStdIn()
      result = transformer.loadNestedEvent(event, context)
    elif (functionName == 'createNextEvent'):
      handlerResponse = readJsonStringFromStdIn()
      event = readJsonStringFromStdIn()
      messageConfig = readJsonStringFromStdIn()
      result = transformer.createNextEvent(handlerResponse, event, messageConfig)
    if (result is not None and len(result) > 0):
      sys.stdout.write(json.dumps(result))
      sys.stdout.flush()
      exitCode = 0
  except LookupError as le:
    sys.stderr.write("Lookup error: " + str(le))
  except:
    sys.stderr.write("Unexpected error:"+ str(sys.exc_info()[0])+ ". " + str(sys.exc_info()[1]))
  sys.exit(exitCode)
