#!/usr/bin/env python
import json
import sys

from message import message

if __name__ == '__main__':
  functionName = sys.stdin.readline().replace('\n', '')
  transformer = message.message()
  exitCode = 1
  try:
    if (functionName == 'loadNestedEvent'):
      event = json.loads(sys.stdin.readline().replace('\n', ''))
      context = json.loads(sys.stdin.readline().replace('\n', ''))
      result = transformer.loadNestedEvent(event, context);
    elif (functionName == 'createNextEvent'):
      nestedResponse = json.loads(sys.stdin.readline().replace('\n', ''))
      event = json.loads(sys.stdin.readline().replace('\n', ''))
      messageConfig = json.loads(sys.stdin.readline().replace('\n', ''))
      result = transformer.createNextEvent(nestedResponse, event, messageConfig);
    elif (functionName == 'loadRemoteEvent'):
      event = json.loads(sys.stdin.readline().replace('\n', ''))
      result = transformer.loadRemoteEvent(event)
    if (result is not None and len(result) > 0):
      sys.stdout.write(json.dumps(result))
      sys.stdout.flush()
      exitCode = 0
  except LookupError as le:
    sys.stderr.write("Lookup error: " + str(le))
  except:
    sys.stderr.write("Unexpected error:"+ str(sys.exc_info()[0])+ ". " + str(sys.exc_info()[1]))
  sys.exit(exitCode)
